### ISSUE TITLE
Is it time to declare `v1` and remove the old factory methods?

### ISSUE THREAD

**Issue by LukeWinikates** [wavefrontHQ/wavefront-sdk-go#98]
The SDK version is currently `0.10.2`, but the SDK is in active use in production environments. Is now the right time to declare a v1?

Also, since the SDK is not yet v1, how will we decide when it is ok to remove the code for the old factory methods and the TCP connection? If we are not actively using these ourselves anymore, maybe it's time to take them out and not carry the burden of the keeping the deprecated functions working.

**Comment by keep94** [comment]
Luke, your idea of parallel http requests sounds interesting. I just wonder how that will work with the Flush() function of a sender object.  When you create a sender, you can effectively turn off autoflushing, send a bunch of metrics and spans which get buffered and flush manually.  Flush() returns an error indicating whether or not everything buffered up was sent successfully.  This sort of use of the API implies just one goroutine using the sender, so I am wondering how a pool of http connections would work.  Are you possibly thinking of rewriting flush to use multiple http connections to do the flushing?

Regarding releasing a v1, I feel that there are several artifacts in the public API that shouldn't be exposed. For instance, I think the functions that convert metrics to strings to be sent over the wire could be made private.


Back to the parallel http requests, if Flush() were rewritten to use multiple http connections, it would still have to block until that last http connection finished sending its portion of metrics/traces because by contract Flush() has to return an error indicating whether or not everything was successfully sent.
